version: '3.8'

services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: mannings-api
    ports:
      - '3001:3001'
    environment:
      - NODE_ENV=production
    depends_on:
      - db

  db:
    image: postgres:latest
    container_name: postgres_db
    ports:
      - '5432:5432'
    environment:
      - POSTGRES_DB=mannings-db
      - POSTGRES_USER=mannings
      - POSTGRES_PASSWORD=123
